In [49]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('../data/loan_data.csv')
data1 = pd.read_csv('../data/Titanic-Dataset.csv')

In [16]:
data.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [21]:
data['ApplicantIncome'].isnull().any()

False

In [28]:
data['CoapplicantIncome'].dtypes

dtype('float64')

In [76]:
for column in data.columns:
    if data[column].isnull().any()==True:
        print(column, data[column].isna().sum(), data[column].dtype, (data[column].isnull().sum()/len(data)*100))

Gender 13 object 2.1172638436482085
Married 3 object 0.4885993485342019
Dependents 15 object 2.44299674267101
Self_Employed 32 object 5.211726384364821
LoanAmount 22 float64 3.5830618892508146
Loan_Amount_Term 14 float64 2.2801302931596092
Credit_History 50 float64 8.143322475570033


In [29]:
data['Gender'].value_counts()

Male      489
Female    112
Name: Gender, dtype: int64

In [36]:
c = data['Gender'].mode()

In [37]:
data['Gender'].fillna(value=c)

0        Male
1        Male
2        Male
3        Male
4        Male
        ...  
609    Female
610      Male
611      Male
612      Male
613    Female
Name: Gender, Length: 614, dtype: object

In [43]:
round(data['LoanAmount'].mean(), 2)

146.41

In [44]:
data['LoanAmount'].fillna(value=146.41)

0      146.41
1      128.00
2       66.00
3      120.00
4      141.00
        ...  
609     71.00
610     40.00
611    253.00
612    187.00
613    133.00
Name: LoanAmount, Length: 614, dtype: float64

In [56]:
from sklearn.impute import SimpleImputer
object_impute = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
object_impute.fit_transform(data[['Gender']])

object_impute1 = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='Male')
object_impute1.fit_transform(data[['Gender']])

array([['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Ma

In [60]:
mean_impute = SimpleImputer(missing_values=np.nan, strategy='mean')

mean_impute.fit_transform(data[['LoanAmount']]).astype('int64')

array([[146],
       [128],
       [ 66],
       [120],
       [141],
       [267],
       [ 95],
       [158],
       [168],
       [349],
       [ 70],
       [109],
       [200],
       [114],
       [ 17],
       [125],
       [100],
       [ 76],
       [133],
       [115],
       [104],
       [315],
       [116],
       [112],
       [151],
       [191],
       [122],
       [110],
       [ 35],
       [120],
       [201],
       [ 74],
       [106],
       [114],
       [320],
       [146],
       [100],
       [144],
       [184],
       [110],
       [ 80],
       [ 47],
       [ 75],
       [134],
       [ 96],
       [ 88],
       [ 44],
       [144],
       [120],
       [144],
       [100],
       [120],
       [112],
       [134],
       [286],
       [ 97],
       [ 96],
       [135],
       [180],
       [144],
       [120],
       [ 99],
       [165],
       [146],
       [116],
       [258],
       [126],
       [312],
       [125],
       [136],
       [172],
      

In [61]:
mean_impute = SimpleImputer(missing_values=np.nan, strategy='median')

mean_impute.fit_transform(data[['LoanAmount']]).astype('int64')

array([[128],
       [128],
       [ 66],
       [120],
       [141],
       [267],
       [ 95],
       [158],
       [168],
       [349],
       [ 70],
       [109],
       [200],
       [114],
       [ 17],
       [125],
       [100],
       [ 76],
       [133],
       [115],
       [104],
       [315],
       [116],
       [112],
       [151],
       [191],
       [122],
       [110],
       [ 35],
       [120],
       [201],
       [ 74],
       [106],
       [114],
       [320],
       [128],
       [100],
       [144],
       [184],
       [110],
       [ 80],
       [ 47],
       [ 75],
       [134],
       [ 96],
       [ 88],
       [ 44],
       [144],
       [120],
       [144],
       [100],
       [120],
       [112],
       [134],
       [286],
       [ 97],
       [ 96],
       [135],
       [180],
       [144],
       [120],
       [ 99],
       [165],
       [128],
       [116],
       [258],
       [126],
       [312],
       [125],
       [136],
       [172],
      

In [67]:
from sklearn.impute import KNNImputer

knn_imputer = KNNImputer(n_neighbors=7, weights='distance')

knn_imputer.fit_transform(data[['LoanAmount']])

array([[146.41216216],
       [128.        ],
       [ 66.        ],
       [120.        ],
       [141.        ],
       [267.        ],
       [ 95.        ],
       [158.        ],
       [168.        ],
       [349.        ],
       [ 70.        ],
       [109.        ],
       [200.        ],
       [114.        ],
       [ 17.        ],
       [125.        ],
       [100.        ],
       [ 76.        ],
       [133.        ],
       [115.        ],
       [104.        ],
       [315.        ],
       [116.        ],
       [112.        ],
       [151.        ],
       [191.        ],
       [122.        ],
       [110.        ],
       [ 35.        ],
       [120.        ],
       [201.        ],
       [ 74.        ],
       [106.        ],
       [114.        ],
       [320.        ],
       [146.41216216],
       [100.        ],
       [144.        ],
       [184.        ],
       [110.        ],
       [ 80.        ],
       [ 47.        ],
       [ 75.        ],
       [134